stages:
  - build
  - deploy
  - release


build apk:
  stage: build
  image: lbry/android-base:platform-28
  before_script:
    - echo "$PGP_PRIVATE_KEY" | gpg --batch --import
    - echo 'deb https://gitsecret.jfrog.io/artifactory/git-secret-deb git-secret main' >> /etc/apt/sources.list
    - wget -qO - 'https://gitsecret.jfrog.io/artifactory/api/gpg/key/public' | apt-key add -
    - apt-get -y update && apt-get -y install build-essential ca-certificates curl git gpg-agent openjdk-8-jdk software-properties-common wget zipalign apksigner git-secret
    - git secret reveal
    - chmod u+x $CI_PROJECT_DIR/gradlew
    - export BUILD_VERSION=$($CI_PROJECT_DIR/gradlew -p $CI_PROJECT_DIR -q printVersionName --console=plain | tail -1)
  artifacts:
    paths:
      - bin/odysee-*-release.apk
    expire_in: 1 week
  script:
    - export PATH=/usr/bin:$PATH
    - export ANDROID_SDK_ROOT=~/.buildozer/android/platform/android-sdk-23
    - chmod u+x ./release.sh
    - ./release.sh
    - cp bin/odysee-$BUILD_VERSION-release.apk /dev/null

deploy build.lbry.io:
  image: python:stretch
  stage: deploy
  dependencies:
    - build apk
  before_script:
    - apt-get -y update && apt-get -y install apt-transport-https
    - echo "$PGP_PRIVATE_KEY" | gpg --batch --import
    - echo 'deb https://gitsecret.jfrog.io/artifactory/git-secret-deb git-secret main' >> /etc/apt/sources.list
    - wget -qO - 'https://gitsecret.jfrog.io/artifactory/api/gpg/key/public' | apt-key add -
    - apt-get -y update && apt-get -y install openjdk-8-jdk git git-secret
    - pip install awscli
    - chmod u+x $CI_PROJECT_DIR/gradlew
    - git secret reveal
    - export BUILD_VERSION=$($CI_PROJECT_DIR/gradlew -p $CI_PROJECT_DIR -q printVersionName --console=plain | tail -1)
    - export BUILD_APK_FILENAME=odysee-$BUILD_VERSION-release.apk
  script:
    - aws s3 cp bin/$BUILD_APK_FILENAME s3://build.lbry.io/android/odysee-build-${CI_PIPELINE_IID}_commit-${CI_COMMIT_SHA:0:7}/$BUILD_APK_FILENAME
    - aws s3 cp bin/$BUILD_APK_FILENAME s3://build.lbry.io/android/odysee-push.apk

release apk:
  image: python:stretch
  stage: release
  only:
    - tags
  dependencies:
    - build apk
  before_script:
    - apt-get -y update && apt-get -y install apt-transport-https
    - echo "$PGP_PRIVATE_KEY" | gpg --batch --import
    - echo 'deb https://gitsecret.jfrog.io/artifactory/git-secret-deb git-secret main' >> /etc/apt/sources.list
    - wget -qO - 'https://gitsecret.jfrog.io/artifactory/api/gpg/key/public' | apt-key add -
    - apt-get -y update && apt-get -y install openjdk-8-jdk git git-secret
    - pip install awscli githubrelease
    - git secret reveal
    - chmod u+x $CI_PROJECT_DIR/gradlew
    - export BUILD_VERSION=$($CI_PROJECT_DIR/gradlew -p $CI_PROJECT_DIR -q printVersionName --console=plain | tail -1)
    - export BUILD_APK_FILENAME=odysee-$BUILD_VERSION-release.apk
  script:
    - githubrelease release lbryio/odysee-android create $CI_COMMIT_TAG --publish bin/$BUILD_APK_FILENAME
    - githubrelease release lbryio/odysee-android edit $CI_COMMIT_TAG --draft
    - aws s3 cp bin/$BUILD_APK_FILENAME s3://build.lbry.io/android/odysee-latest.apk